[package]
name = "amqp-lapin-helper"
description = "rust lapin helper"
license = "MIT"
version = "0.1.1"
authors = ["Jonathan Dizdarevic <dizzda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "1.7.1"
tokio-amqp = "1.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
async-trait = "0.1.51"
tokio = { version = "1.10.1", features = ["full"] } # TODO: downgrade dependencies
once_cell = "1.8.0"
futures-lite = "1.12.0"
thiserror = "1.0.28"
log = "0.4.14"
anyhow = "1.0.38"
chrono = "0.4.19"
uuid = { version = "0.8.2", features = ["serde"] }
bincode = "1.3.3"
