[package]
name = "amqp-lapin-helper"
description = "rust lapin helper"
license = "MIT"
version = "0.5.3"
authors = ["Jonathan Dizdarevic <dizzda@gmail.com>"]
edition = "2021"
repository = "https://github.com/dizda/amqp-lapin-helper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "2.2.1"
tokio-amqp = "2.0.0"
serde = { version = "1.0.164", features = ["derive"] }
async-trait = "0.1.68"
tokio = { version = "1.28.2", features = ["sync", "macros"] }
once_cell = "1.18.0"
futures-lite = "1.13.0"
thiserror = "1.0.40"
tracing = "0.1.37"
chrono = "0.4.26"
uuid = { version = "0.8.2", features = ["serde"] }
bincode = "1.3.3"
prometheus = { version = "0.13.3", features = [] }
