[package]
name = "amqp-lapin-helper"
description = "rust lapin helper"
license = "MIT"
version = "0.5.0"
authors = ["Jonathan Dizdarevic <dizzda@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "2.1.1"
tokio-amqp = "2.0.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
async-trait = "0.1.64"
tokio = { version = "1.25.0", features = ["sync"] }
once_cell = "1.17.0"
futures-lite = "1.12.0"
thiserror = "1.0.38"
tracing = "0.1.37"
chrono = "0.4.23"
uuid = { version = "0.8.2", features = ["serde"] }
bincode = "1.3.3"
prometheus = { version = "0.13.3", features = [] }
