[package]
name = "amqp-lapin-helper"
description = "rust lapin helper"
license = "MIT"
version = "0.2.2"
authors = ["Jonathan Dizdarevic <dizzda@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "1.9.0"
tokio-amqp = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
async-trait = "0.1.52"
tokio = { version = "1.17.0", features = [] }
once_cell = "1.9.0"
futures-lite = "1.12.0"
thiserror = "1.0.30"
log = "0.4.14"
anyhow = "1.0.51"
chrono = "0.4.19"
uuid = { version = "0.8.2", features = ["serde"] }
bincode = "1.3.3"
