[package]
name = "amqp-lapin-helper"
description = "rust lapin helper"
license = "MIT"
version = "0.3.0"
authors = ["Jonathan Dizdarevic <dizzda@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "1.10.0"
tokio-amqp = "1.1.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
async-trait = "0.1.60"
tokio = { version = "1.23.0", features = ["sync"] }
once_cell = "1.17.0"
futures-lite = "1.12.0"
thiserror = "1.0.38"
log = "0.4.17"
anyhow = "1.0.68"
chrono = "0.4.23"
uuid = { version = "0.8.2", features = ["serde"] }
bincode = "1.3.3"
prometheus = { version = "0.13.3", features = [] }
